### ISSUE TITLE
Non-ASCII filenames

### ISSUE THREAD

**Issue by mlinksva** [socs-dev-env/dosocs2#95]
DoSOCSv2 seems to be not be able to handle non-ASCII filenames. Example, clone https://github.com/gjtorikian/html-proofer.git which contains `spec/html-proofer/fixtures/links/erstiebegrüßung.html`:

```
# dosocs2 oneshot html-proofer
Traceback (most recent call last):
  File "/usr/local/bin/dosocs2", line 9, in <module>
    load_entry_point('dosocs2==0.16.1', 'console_scripts', 'dosocs2')()
  File "/usr/local/lib/python2.7/dist-packages/dosocs2/dosocs2.py", line 336, in main
    package = do_scan(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dosocs2/dosocs2.py", line 127, in do_scan
    package = spdxdb.register_package(conn, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dosocs2/spdxdb.py", line 148, in register_package
    bulk_insert(conn, db.packages_files, row_params)
  File "/usr/local/lib/python2.7/dist-packages/dosocs2/spdxdb.py", line 38, in bulk_insert
    conn.execute(table.insert(), *rows_list)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 459, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. [SQL: u'INSERT INTO packages_files (package_id, file_id, concluded_license_id, license_comment, file_name) VALUES (?, ?, ?, ?, ?)'] [parameters: ((4, 2000, None, '', './spec/html-proofer/fixtures/favicon/favicon_broken_but_ignored.html'), (4, 129, None, '', './spec/html-proofer/fixtures/links/erstiebegru\xcc\x88\xc3\x9fung.html'), (4, 2001, None, '', './spec/html-proofer/fixtures/vcr_cassettes/links/attributeWithDash_html_log_level_error_type_file_.yml'), (4, 2002, None, '', './spec/html-proofer/fixtures/images/terribleImageName.html'), (4, 2003, None, '', './lib/html-proofer/check.rb'), (4, 2004, None, '', './spec/html-proofer/fixtures/images/missingImageSrc.html'), (4, 2005, None, '', './Rakefile'), (4, 2006, None, '', './spec/html-proofer/fixtures/links/brokenHashInternal.html')  ... displaying 10 of 292 total bound parameter sets ...  (4, 2262, None, '', './spec/html-proofer/fixtures/utils/lang-jp.html'), (4, 2263, None, '', './spec/html-proofer/fixtures/html/html5_tags.html'))]
```

Or download archive and:

```
# dosocs2 oneshot html-proofer-master.zip 
Traceback (most recent call last):
  File "/usr/local/bin/dosocs2", line 9, in <module>
    load_entry_point('dosocs2==0.16.1', 'console_scripts', 'dosocs2')()
  File "/usr/local/lib/python2.7/dist-packages/dosocs2/dosocs2.py", line 328, in main
    with util.tempextract(package_path) as (tempdir, _):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/dosocs2/util.py", line 107, in tempextract
    zf.extractall(path=tempdir)
  File "/usr/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/lib/python2.7/zipfile.py", line 1083, in _extract_member
    file(targetpath, "wb") as target:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 78-79: ordinal not in range(128)
```

**Comment by ghost** [comment]
@mlinksva Similar issue was identified and is awaiting a merger [pull request 92](https://github.com/DoSOCSv2/DoSOCSv2/pull/92)

I will re-verify this issue by cloning and scanning against https://github.com/gjtorikian/html-proofer.git
